"""
Customer Experience Intelligence Agent
=======================================
Usage:
    python main.py 12345
    python main.py 99001
    python main.py          # defaults to customer 12345

Runs 5 LangGraph nodes:
  discover_profile → analyze_behavior → generate_recommendations → visualize → compose_engagement

Each run is written to its own directory under runs/:
  runs/{customer_id}_{timestamp}/
    agent.log                — full DEBUG log
    sql_queries.txt          — all SQL generated by CRAFT (evidence trail)
    customer_profile.json    — demographics row from USERS
    purchase_history.json    — recent orders × product details
    category_preferences.json— top categories by spend
    behavior_events.json     — event_type distribution
    recommended_products.json— top recommended products
    offer_candidates.json    — high-margin items for targeted offers
    preference_chart.json    — Plotly figure spec: spend by category
    preference_chart.png     — chart image (attach to Confluence / email)
    recommendation_chart.json— Plotly figure spec: recommended products × price
    recommendation_chart.png — chart image (attach to Confluence / email)
    engagement_brief.md      — personalized engagement report (Gemini)
                               includes: snapshot, top-3 recommendations, offers, triggers
"""
import asyncio
import json
import logging
import sys
from datetime import datetime
from pathlib import Path

import plotly.io as pio

from rich.console import Console
from rich.markdown import Markdown
from rich.panel import Panel
from rich.rule import Rule

from config import CRAFT_MCP_URL, GEMINI_SYNTHESIS_MODEL
from craft_client import CraftClient
from graph import build_graph
from state import CustomerExperienceAgentState

console = Console()

_DEFAULT_CUSTOMER_ID = 12345


def _create_run_dir(customer_id: int) -> Path:
    """Create a unique run directory under runs/ for this invocation."""
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    run_dir = Path("runs") / f"customer_{customer_id}_{timestamp}"
    run_dir.mkdir(parents=True, exist_ok=True)
    return run_dir


def _setup_logging(run_dir: Path) -> None:
    """Configure logging: DEBUG to run_dir/agent.log, WARNING+ to stderr."""
    log_file = run_dir / "agent.log"

    root = logging.getLogger()
    root.setLevel(logging.DEBUG)

    file_handler = logging.FileHandler(log_file)
    file_handler.setLevel(logging.DEBUG)
    file_handler.setFormatter(logging.Formatter(
        "%(asctime)s  %(levelname)-8s  %(name)s  %(message)s",
        datefmt="%H:%M:%S",
    ))

    stderr_handler = logging.StreamHandler(sys.stderr)
    stderr_handler.setLevel(logging.WARNING)
    stderr_handler.setFormatter(logging.Formatter("%(levelname)s %(message)s"))

    root.addHandler(file_handler)
    root.addHandler(stderr_handler)

    for noisy_logger in ("httpx", "httpcore", "langgraph", "google", "choreographer", "kaleido"):
        logging.getLogger(noisy_logger).setLevel(logging.WARNING)


def _save_run_artifacts(run_dir: Path, final: CustomerExperienceAgentState) -> None:
    """Persist all intermediate data and outputs for this run."""

    # SQL audit trail
    sql_queries = final.get("sql_queries", [])
    if sql_queries:
        sql_path = run_dir / "sql_queries.txt"
        sql_path.write_text(
            "\n\n".join(f"-- Q{i + 1}\n{sql}" for i, sql in enumerate(sql_queries))
        )

    # JSON data artifacts
    json_artifacts: list[tuple[str, str]] = [
        ("customer_profile.json",        "customer_profile"),
        ("purchase_history.json",        "purchase_history"),
        ("category_preferences.json",    "category_preferences"),
        ("behavior_events.json",         "behavior_events"),
        ("recommended_products.json",    "recommended_products"),
        ("offer_candidates.json",        "offer_candidates"),
    ]
    for filename, state_key in json_artifacts:
        data = final.get(state_key)
        if data:
            (run_dir / filename).write_text(json.dumps(data, indent=2))

    # Plotly chart specs — saved as JSON and rendered to PNG
    chart_artifacts: list[tuple[str, str]] = [
        ("preference_chart",     "preference_chart"),
        ("recommendation_chart", "recommendation_chart"),
    ]
    for stem, state_key in chart_artifacts:
        chart = final.get(state_key)
        if chart:
            (run_dir / f"{stem}.json").write_text(json.dumps(chart, indent=2))
            try:
                fig = pio.from_json(json.dumps(chart))
                pio.write_image(fig, str(run_dir / f"{stem}.png"), format="png", width=1200, height=600)
            except Exception as exc:
                log.warning(f"Could not render {stem} to PNG: {exc}")

    # Engagement brief
    brief = final.get("engagement_brief", "")
    if brief:
        (run_dir / "engagement_brief.md").write_text(brief)


async def run(customer_id: int) -> CustomerExperienceAgentState:
    run_dir = _create_run_dir(customer_id)
    _setup_logging(run_dir)

    console.print()
    console.print(Panel(
        f"[bold blue]Customer Experience Intelligence Agent[/bold blue]\n\n"
        f"  Customer ID  : [yellow bold]{customer_id}[/yellow bold]\n"
        f"  CRAFT MCP    : [dim]{CRAFT_MCP_URL}[/dim]\n"
        f"  Synthesis LLM: [dim]{GEMINI_SYNTHESIS_MODEL}[/dim]\n"
        f"  Flow         : [dim]discover_profile → analyze_behavior → "
        f"generate_recommendations → visualize → compose_engagement[/dim]\n"
        f"  Run dir      : [dim]{run_dir}/[/dim]",
        expand=False,
    ))

    craft = CraftClient()
    graph = build_graph(craft)

    initial_state: CustomerExperienceAgentState = {
        "customer_id":          customer_id,
        "schema_summary":       "",
        "tables_available":     [],
        "customer_profile":     {},
        "purchase_history":     [],
        "category_preferences": [],
        "behavior_events":      [],
        "sql_queries":          [],
        "recommended_products": [],
        "offer_candidates":     [],
        "preference_chart":     {},
        "recommendation_chart": {},
        "engagement_brief":     "",
        "iteration":            0,
        "errors":               [],
        "status":               "running",
    }

    final_state: CustomerExperienceAgentState = await graph.ainvoke(initial_state)

    _save_run_artifacts(run_dir, final_state)

    # ── Evidence trail ────────────────────────────────────────────────────────
    console.print()
    console.print(Rule("[dim]Evidence Trail — SQL generated by CRAFT[/dim]"))
    for i, sql in enumerate(final_state.get("sql_queries", []), 1):
        console.print(f"  [dim]Q{i}:[/dim] {sql[:110]}{'…' if len(sql) > 110 else ''}")

    if final_state.get("errors"):
        console.print("\n[yellow]Warnings:[/yellow]")
        for error in final_state["errors"]:
            console.print(f"  [yellow]⚠[/yellow]  {error}")

    # ── Engagement brief ──────────────────────────────────────────────────────
    if final_state.get("engagement_brief"):
        console.print()
        customer_name = (
            final_state.get("customer_profile", {}).get("first_name", f"Customer {customer_id}")
        )
        console.print(Panel(
            Markdown(final_state["engagement_brief"]),
            title=f"[bold green]Engagement Brief — {customer_name}[/bold green]",
            border_style="green",
            padding=(1, 2),
        ))

    # ── Run summary ───────────────────────────────────────────────────────────
    console.print()
    console.print(Rule("[dim]Run Artifacts[/dim]"))
    for artifact in sorted(run_dir.iterdir()):
        size = artifact.stat().st_size
        console.print(f"  [green]✓[/green] {artifact.name:<35} ({size:,} bytes)")
    console.print(f"\n  [dim]Full run: {run_dir}/[/dim]")
    console.print(
        f"\n  Charts saved as PNG:\n"
        f"  [dim]{run_dir}/preference_chart.png\n"
        f"  {run_dir}/recommendation_chart.png[/dim]"
    )

    return final_state


if __name__ == "__main__":
    raw_id = sys.argv[1] if len(sys.argv) > 1 else str(_DEFAULT_CUSTOMER_ID)
    try:
        parsed_customer_id = int(raw_id)
    except ValueError:
        console.print(f"[red]Error:[/red] customer_id must be an integer, got '{raw_id}'")
        sys.exit(1)

    asyncio.run(run(parsed_customer_id))
